//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceTxnHist
    {
        public string MemberID { get; set; }
        public string TXN_SN { get; set; }
        public string Source { get; set; }
        public string RegiNo { get; set; }
        public string TradeSeqNo { get; set; }
        public int Amount_add { get; set; }
        public int Amount_del { get; set; }
        public string Annual { get; set; }
        public System.DateTime DataDate { get; set; }
        public System.DateTime TxnDate { get; set; }
        public string BDate { get; set; }
        public int LastBalance { get; set; }
        public int Balance { get; set; }
        public int Price { get; set; }
        public string CrmFlag { get; set; }
        public Nullable<System.DateTime> CrmBAT { get; set; }
        public Nullable<int> SubTotal { get; set; }
        public string InvNoS { get; set; }
        public string InvNoE { get; set; }
        public string Cashier { get; set; }
    }
}
