//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDTBL
    {
        public string CCODE { get; set; }
        public string CITEM { get; set; }
        public string SUBITEM { get; set; }
        public string CNAME { get; set; }
        public string CNOTE { get; set; }
        public System.DateTime UPDT { get; set; }
        public string UPUSER { get; set; }
    }
}
