//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COSMEDEntities : DbContext
    {
        public COSMEDEntities()
            : base("name=COSMEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BalanceExchange> BalanceExchange { get; set; }
        public DbSet<BalanceTxnHist> BalanceTxnHist { get; set; }
        public DbSet<Members> Members { get; set; }
        public DbSet<TENPO> TENPO { get; set; }
        public DbSet<ITEM_DEF> ITEM_DEF { get; set; }
    }
}
