//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public string MemberID { get; set; }
        public string OldMemberID { get; set; }
        public int OldCardPoint { get; set; }
        public string NewMemberID { get; set; }
        public int NewCardPoint { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string birthDate { get; set; }
        public string PhoneM { get; set; }
        public string PhoneN { get; set; }
        public string Mobile { get; set; }
        public string ZipCodeL { get; set; }
        public string AddressL { get; set; }
        public string ZipCodeC { get; set; }
        public string AddressC { get; set; }
        public string CareerNo { get; set; }
        public string EduNo { get; set; }
        public string Income { get; set; }
        public string Children { get; set; }
        public string Email1 { get; set; }
        public string EMail2 { get; set; }
        public string MemberClass { get; set; }
        public string Rank { get; set; }
        public string AnnPromo { get; set; }
        public string CoerPromo { get; set; }
        public string Remarks { get; set; }
        public string STNID { get; set; }
        public string CreateDate { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public string Password { get; set; }
        public string PassChecked { get; set; }
        public string UpdateUser { get; set; }
        public string UpdateSTNID { get; set; }
        public System.DateTime DsplDate { get; set; }
        public string CrmFlag { get; set; }
        public string RecvMsgFlag { get; set; }
        public string MbrMaintain { get; set; }
        public Nullable<System.DateTime> MbrMainDT { get; set; }
        public string MbrAgree { get; set; }
        public string FirstDe { get; set; }
    }
}
