//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetails>();
            this.ReceiptDetails = new HashSet<ReceiptDetails>();
            this.TransferDetails = new HashSet<TransferDetails>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> LastReceiptDate { get; set; }
        public Nullable<System.DateTime> LastDeliveryDate { get; set; }
        public Nullable<bool> StopSales { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public byte[] Picture { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<DeliveryDetails> DeliveryDetails { get; set; }
        public virtual ICollection<ReceiptDetails> ReceiptDetails { get; set; }
        public virtual ICollection<TransferDetails> TransferDetails { get; set; }
    }
}
