//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_DAILY_ITEM_CTGRY_MBR_E
    {
        public string CORP_CD { get; set; }
        public string MBR_ID { get; set; }
        public string TRAN_DATE { get; set; }
        public string BCAT_CD { get; set; }
        public string MCAT_CD { get; set; }
        public string SCAT_CD { get; set; }
        public string TCAT_CD { get; set; }
        public string CORP_NAME { get; set; }
        public string BCAT_NAME { get; set; }
        public string MCAT_NAME { get; set; }
        public string SCAT_NAME { get; set; }
        public string TCAT_NAME { get; set; }
        public string AGE { get; set; }
        public string MARRIAGE { get; set; }
        public string CHILD { get; set; }
        public string VOCATION { get; set; }
        public Nullable<long> PURCHASE_CNT { get; set; }
        public Nullable<long> PURCHASE_PRICE { get; set; }
        public Nullable<long> PURCHASE_QTY { get; set; }
        public string BCAT_FCD { get; set; }
        public string MCAT_FCD { get; set; }
        public string SCAT_FCD { get; set; }
        public string TCAT_FCD { get; set; }
        public string GENDER { get; set; }
    }
}
