//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TENPO
    {
        public string STNID { get; set; }
        public string STNNAME { get; set; }
        public string DST_FLAG { get; set; }
        public string OPEN_YMD { get; set; }
        public string CLOSE_YMD { get; set; }
        public string DST_YMD { get; set; }
        public System.DateTime DataDate { get; set; }
        public string CHIIKI_CD { get; set; }
        public string PLACE_KBN { get; set; }
        public string GROUP_CD { get; set; }
    }
}
