//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class XINEntities : DbContext
    {
        public XINEntities()
            : base("name=XINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Delivery> Delivery { get; set; }
        public DbSet<DeliveryDetails> DeliveryDetails { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Programs> Programs { get; set; }
        public DbSet<Receipt> Receipt { get; set; }
        public DbSet<ReceiptDetails> ReceiptDetails { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<Transfer> Transfer { get; set; }
        public DbSet<TransferDetails> TransferDetails { get; set; }
        public DbSet<UserAuthority> UserAuthority { get; set; }
        public DbSet<XINUsers> XINUsers { get; set; }

        public virtual ObjectResult<sp_Customer_Orders_Result> sp_Customer_Orders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Customer_Orders_Result>("sp_Curstomer_Orders");
        }
    }
}
